### ISSUE TITLE
invalid algorithm when trying to validate using the jsonwebtoken package

### ISSUE THREAD

**Issue by antback** [qbhy/simple-jwt#15]
Hi,

First of all, thanks for the package :-)

I'm having an issue when validating a jwt generated with the nodejs package jsonwebtoken. It throws: "invalid algorithm".

This is my config in hyperf:

<pre>
            /*
             * Optional
             * The default encryption class used
             */
            'default' => Encrypter\HS256Encrypter::class,

            /*
             * Optional
             * Encryption class must implement Qbhy\SimpleJwt\Interfaces\Encrypter interface
             */
            'drivers' => [
                Encrypter\HS256Encrypter::alg() => Encrypter\HS256Encrypter::class,
                Encrypter\PasswordHashEncrypter::alg() => Encrypter\PasswordHashEncrypter::class,
                Encrypter\CryptEncrypter::alg() => Encrypter\CryptEncrypter::class,
                Encrypter\SHA1Encrypter::alg() => Encrypter\SHA1Encrypter::class,
                Encrypter\Md5Encrypter::alg() => Encrypter\Md5Encrypter::class,
            ],

            /*
             * Optional
             * Encoding class
             */
            'encoder' => new Encoders\Base64UrlSafeEncoder(),
            // 'encoder' => new Encoders\Base64Encoder(),

</pre>

This is the nodejs program:

<pre>
const jwt = require('jsonwebtoken');

actualToken="eyJ0eXAiOiJqd3QifQ.eyJzdWIiOiJ0ZXN0IiwiaXNzIjoiaHR0cDpcL1wvOjk1MDEiLCJleHAiOjE3Mjc0MjgzMTEsImlhdCI6MTcyNzM0MTkxMSwibmJmIjoxNzI3MzQxOTExLCJzY29wZXMiOiJiYXNpYzpwb2MiLCJ1aWQiOjEsInMiOiJCVm9NNkkiLCJqdGkiOiIyODc3M2MyMWFjNTMzNzBkMTQ0MGQ1OTg5ODY1NzMyMCJ9.27NvzT3303vzRSpr8s6JbH_tmhm9BrNLCn07eCunj_c"
secret="hello"

// Verify the token using the secret and HMAC algorithm (HS256 by default)
jwt.verify(actualToken, secret, (err, decoded) => {
    if (err) {
        console.log('Token is invalid', err)
    } else {
        console.dir(decoded);
    }
});

</pre>

Do you know where is the problem?

Thanks.

PD: Pasting the token in https://jwt.io/ shows invalid signature.

**Comment by antback** [comment]
Ok, after some investigation is seems that the problem is that the JWT header does not contain the `alg` attribute. Is there any way of including it?

<img width="612" alt="image" src="https://github.com/user-attachments/assets/69d744f6-4f01-42df-9cd7-e489b94d4235">


Thanks.

**Comment by antonioskyc** [comment]
Hi,

I have resolved the issue by defining a custom Guard and supplying the header like this:

<pre>
class MyCustomJwtGuard extends JwtGuard
{
    /**
     * @var JWTManager
     */
    protected $jwtManager;

    /**
     * @var RequestInterface
     */
    protected $request;

    protected $headerName = 'Authorization';

    public function login(Authenticatable $user, array $payload = [])
    {
        $token = $this->getJwtManager()->make(
            array_merge($payload, [
            'uid' => $user->getId(),
            's' => str_random(),
            ]), 
            ["alg" => $this->getJwtManager()->getEncrypter()->alg()])->token();

        return $token;
    }

}
</pre>

Regards.

**Comment by antback** [comment]
Hi,

I have resolved the issue by defining a custom Guard and supplying the header like this:

<pre>
class MyCustomJwtGuard extends JwtGuard
{
    /**
     * @var JWTManager
     */
    protected $jwtManager;

    /**
     * @var RequestInterface
     */
    protected $request;

    protected $headerName = 'Authorization';

    public function login(Authenticatable $user, array $payload = [])
    {
        $token = $this->getJwtManager()->make(
            array_merge($payload, [
            'uid' => $user->getId(),
            's' => str_random(),
            ]), 
            ["alg" => $this->getJwtManager()->getEncrypter()->alg()])->token();

        return $token;
    }
}
</pre>

Regards.
